# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c9a5f67229f04dc124d23d108580b1c549cd8caf5233355ca1373dceca2acee0436645577d29b04a137009304716f096a4906020b0cf8cfd0e531acd4da04e7

test:
  secret_key_base: 1961d7fda61e461af7c70a83a8b177d86f0e43a713936899b5a7c30b5e4f6e888f64a5a361aa9fe75b52250d2cf330bec583320529bac768497772f1588fde50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
